### ISSUE TITLE
List of extensions is not Rackspace-specific for Cloud Servers

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-api-reference#39]
The extensions returned by Rackspace cloud is not the same as a generic OpenStack installation, so the example json returned should be substituted with this instead: 

{"extensions": [{"updated": "2011-09-27T00:00:00+00:00", "name": "DiskConfig", "links": [], "namespace": "http://docs.openstack.org/compute/ext/disk_config/api/v1.1", "alias": "OS-DCF", "description": "Disk Management Extension."}, {"updated": "2013-02-19T00:00:00+00:00", "name": "ImageSize", "links": [], "namespace": "http://docs.openstack.org/compute/ext/image_size/api/v1.1", "alias": "OS-EXT-IMG-SIZE", "description": "Adds image size to image listings."}, {"updated": "2011-11-03T00:00:00+00:00", "name": "ExtendedStatus", "links": [], "namespace": "http://docs.openstack.org/compute/ext/extended_status/api/v1.1", "alias": "OS-EXT-STS", "description": "Extended Status support."}, {"updated": "2011-09-14T00:00:00+00:00", "name": "FlavorExtraData", "links": [], "namespace": "http://docs.openstack.org/compute/ext/flavor_extra_data/api/v1.1", "alias": "OS-FLV-EXT-DATA", "description": "Provide additional data for flavors."}, {"updated": "2013-08-01T00:00:00+00:00", "name": "FlavorWithExtraSpecs", "links": [], "namespace": "http://docs.openstack.org/compute/ext/flavor_with_extra_specs/api/v2.0", "alias": "OS-FLV-WITH-EXT-SPECS", "description": "Provide extra specs along with flavor data."}, {"updated": "2013-07-08T00:00:00+00:00", "name": "BlockDeviceMappingV2Boot", "links": [], "namespace": "http://docs.openstack.org/compute/ext/block_device_mapping_v2_boot/api/v2", "alias": "os-block-device-mapping-v2-boot", "description": "Allow boot with the new BDM data format."}, {"updated": "2012-07-16T00:00:00+00:00", "name": "ConfigDrive", "links": [], "namespace": "http://docs.openstack.org/compute/ext/config_drive/api/v1.1", "alias": "os-config-drive", "description": "Config Drive Extension."}, {"updated": "2011-12-23T00:00:00+00:00", "name": "Consoles", "links": [], "namespace": "http://docs.openstack.org/compute/ext/os-consoles/api/v2", "alias": "os-consoles", "description": "Interactive Console support."}, {"updated": "2011-06-23T00:00:00+00:00", "name": "FlavorExtraSpecs", "links": [], "namespace": "http://docs.openstack.org/compute/ext/flavor_extra_specs/api/v1.1", "alias": "os-flavor-extra-specs", "description": "Instance type (flavor) extra specs."}, {"updated": "2012-08-29T00:00:00+00:00", "name": "FlavorRxtx", "links": [], "namespace": "http://docs.openstack.org/compute/ext/flavor_rxtx/api/v1.1", "alias": "os-flavor-rxtx", "description": "Support to show the rxtx status of a flavor."}, {"updated": "2012-08-29T00:00:00+00:00", "name": "FlavorSwap", "links": [], "namespace": "http://docs.openstack.org/compute/ext/flavor_swap/api/v1.1", "alias": "os-flavor-swap", "description": "Support to show the swap status of a flavor."}, {"updated": "2013-02-08T00:00:00+00:00", "name": "InstanceActions", "links": [], "namespace": "http://docs.openstack.org/compute/ext/instance-actions/api/v1.1", "alias": "os-instance-actions", "description": "View a log of actions and events taken on an instance."}, {"updated": "2011-08-08T00:00:00+00:00", "name": "Keypairs", "links": [], "namespace": "http://docs.openstack.org/compute/ext/keypairs/api/v1.1", "alias": "os-keypairs", "description": "Keypair Support."}, {"updated": "2012-03-07T09:46:43-05:00", "name": "OSNetworksV2", "links": [], "namespace": "http://docs.openstack.org/ext/services/api/v1.1", "alias": "os-networksv2", "description": "Admin-only Network Management Extension."}, {"updated": "2011-08-18T00:00:00+00:00", "name": "Rescue", "links": [], "namespace": "http://docs.openstack.org/compute/ext/rescue/api/v1.1", "alias": "os-rescue", "description": "Instance rescue mode."}, {"updated": "2012-07-13T00:00:00+00:00", "name": "UsedLimits", "links": [], "namespace": "http://docs.openstack.org/compute/ext/used_limits/api/v1.1", "alias": "os-used-limits", "description": "Provide data on limited resources that are being used."}, {"updated": "2012-08-07T00:00:00+00:00", "name": "UserData", "links": [], "namespace": "http://docs.openstack.org/compute/ext/userdata/api/v1.1", "alias": "os-user-data", "description": "Add user_data to the Create Server v1.1 API."}, {"updated": "2011-08-17T00:00:00+00:00", "name": "VirtualInterfaces", "links": [], "namespace": "http://docs.openstack.org/compute/ext/virtual_interfacesv2/api/v1.1", "alias": "os-virtual-interfacesv2", "description": "Virtual interface support."}, {"updated": "2011-03-25T00:00:00+00:00", "name": "Volumes", "links": [], "namespace": "http://docs.openstack.org/compute/ext/volumes/api/v1.1", "alias": "os-volumes", "description": "Volumes support."}, {"updated": "2013-03-20T00:00:00+00:00", "name": "ScheduledImages", "links": [], "namespace": "http://docs.openstack.org/servers/api/ext/scheduled_images/v1.0", "alias": "rax-si-image-schedule", "description": "Enables automatic scheduled images to be taken of a server."}]}

**Comment by catlook** [comment]
fixed and published!
